# Copyright (C) 2023  Horimoto Yasuhiro <horimoto@clear-code.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.

name: Tests-Windows
on:
  - push
  - pull_request
jobs:
  test:
    name: Tests-Windows
    strategy:
      fail-fast: false
      matrix:
        raku-version:
          - "2023.08-01"
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: echo-test
        run: |
          $revision = git describe --abbrev=7 HEAD
          Write-Output "Hello World!"
          Write-Output "${revision}"
